name: ScratchWorlds
main: com.lithium3141.ScratchWorlds.ScratchWorlds
author: lithium3141
version: 0.1
database: false
commands:
    scratch:
        description: Manipulate worlds used as scratch
        usage: /<command> list
